### ISSUE TITLE
App lag

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/europe-covid-forecast#10]
For me this week the app was effectively unusable due to variable amounts of lag coupled with chaining presses once the app responded (for example taking 30 seconds to submit a forecast and then entering an infinite loop over countries and targets). 

I managed forecasts for the UK, Germany, and Poland but I am not clear if any actually went through or if others were submitted. 

Probably need to optimise the app for higher loads and bump up the server in the short term.

**Comment by nikosbosse** [comment]
Closing as we weren't able to do anything about it / reproduce it

**Comment by seabbs** [comment]
Good idea. I did some internet testing and this was definitely just a slow connection issue
