### ISSUE TITLE
Possible mistake with german case number for 2021-03-20

### ISSUE THREAD

**Issue by AurelWu** [epiforecasts/europe-covid-forecast#15]
It's possibly a mistake on my side but using the numbers from https://www.ecdc.europa.eu/en/publications-data/data-daily-new-cases-covid-19-eueea-country , the 7-day sum of cases in germany (14th to 20th March) is around 87.000 rather than the 102.000 which is displayed as actual value. I checked Austria and Finland to compare, and for those both the sums fit pretty closely with ECDC Data from today.
Best Regards, Aurel

**Comment by AurelWu** [comment]
Datum | ECML | ECDC
13/03/2021 | 12674 | 12674
14/03/2021 | 10790 | 10790
15/03/2021 | 6604 | 6604
16/03/2021 | 5480 | 5480
17/03/2021 | 30939 | 13435
19/03/2021 | 17482 | 17504
20/03/2021 | 16033 | 17482
21/03/2021 | 13733 | 16033

Maybe the problem is that ECML did combine values of 17.03 and 18.03 and skipped the 18.03 entirely

**Comment by nikosbosse** [comment]
Hi Aurel, thank you very much for raising this!
So there was indeed an error and the "correct" number should be 99369. That, at least is the weekly case numbers according to JHU. 

![image](https://user-images.githubusercontent.com/37978797/112141382-82948b00-8bd5-11eb-8e91-f36bacc25b5f.png)

However, I agree that this number is still 10k above what other sources say. We're investigating further. I'll keep you posted!

**Comment by nikosbosse** [comment]
Hi Aurel, 
So I think this issue really is with JHU (and it might be appropriate to create an issue there) and I'm not sure we have anything we or the ECDC Forecast Hub really can do about it at the moment. Unfortunately messy data is part of the job... 

My suggestion would be to close this issue for now and hope that data will be correct in the future. Please feel free to reopen it if you have suggestions for any action we could take. 

Thank you very much for your continued participation and your feedback, we very much appreciate it!

**Comment by nikosbosse** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/3857
