### ISSUE TITLE
Get rid of covid.german.forecast package calls

### ISSUE THREAD

**Issue by nikosbosse** [epiforecasts/europe-covid-forecast#18]
replace by ecdc version

Ultimately, we should make a separate package

**Comment by seabbs** [comment]
https://github.com/epiforecasts/europe-covid-forecast/search?q=covid.german.forecast

**Comment by nikosbosse** [comment]
maybe it's just on my local computer... Need to make the package switch anyway at some piont

**Comment by seabbs** [comment]
if its on your local computer then your git must be very confusing....
