### ISSUE TITLE
Adapt locations.rda file

### ISSUE THREAD

**Issue by nikosbosse** [epiforecasts/europe-covid-forecast#2]
ECDC locations are here: https://raw.githubusercontent.com/epiforecasts/covid19-forecast-hub-europe/main/data-locations/locations_eu.csv

**Comment by seabbs** [comment]
I killed this for now as we are pulling directly from the hub store for all use cases. perhaps we should save and use from that location.

**Comment by nikosbosse** [comment]
Isn't that part of the pacakge now?

**Comment by seabbs** [comment]
Its been taken out and we directly download from the hub but yup that means can close.

**Comment by nikosbosse** [comment]
Ah ok. I think I added it back in because one of the scripts didn't run (it
was missing the locations). I'll have a look again later

Sam Abbott ***@***.***> schrieb am Mi., 17. März 2021, 10:34:
