### ISSUE TITLE
This week's submission

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/europe-covid-forecast#8]
I don't really have the bandwidth for this this week. Nikos can you handle submitting the model stuff + debugging if it fails (ideally it won't)? I'll do the expert stuff for some subset of countries as usual of course.

**Comment by nikosbosse** [comment]
will do. 
I think the tasks are all scheduled, aren't they? I scheduled all the crowd stuff, but haven't look at the models. 
So hopefully all goes smoothly. 
Germany and Poland would probably make the Hub people over there happy, but otherwise no preference for countries, so don't feel obliged

**Comment by seabbs** [comment]
Everything should be scheduled and I'd like to not miss a week ideally. Should just be logging into the server and doing the submit script but of something fails might need to check the logs and do a light debug. I'm pretty confident it will be fine though...
